apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: elasticsearch-client-bundle
    description: Elasticsearch Client bundle provides a central configuration and
        factory feature for creating elasticsearch clients to be used in other
        OpenDXP bundles.
spec:
    type: library
    lifecycle: production
    owner: team-opendxp
    system: opendxp
